name: testcicd

on: 
  push:
    branches: [ master ]

jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v1 #tien ich CLI mo rong conmand, tang hieu nang docker cmd
        id: buildx

      - name: Build and Push Image
        run: docker build -t duy71/myimage -f Dockerfile .
        run: docker push duy71/myimage


#      - name: Build and Push Docker Image
#        uses: docker/build-push-acion@v2
#        id: docker_build
#        with:
#          context: ./
#          dockerfile: ./Dockerfile
#          builder: ${{ steps.buildx.outputs.name }}
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/githubcicd

#      - name: Verify
#        run: echo ${{ steps.docker_build.outputs.digest }}
      